@startuml

!define SHOW_PRECONNECT
!define SHOW_CONNECT
!define SHOW_DISCONNECT

skinparam backgroundColor #000000
skinparam shadowing false
skinparam sequenceArrowThickness 2

skinparam sequence {
    ArrowColor #FF9300
    ArrowFontName "Iosevka SS08"
    ArrowFontColor #FFFFFF
    
    DelayFontName "Iosevka SS08"
    DelayFontColor #FFFFFF

    LifeLineBorderColor #FF9300
    LifeLineBackgroundColor #FF9300

    ParticipantBorderColor #FF9300
    ParticipantBackgroundColor #000000
    ParticipantFontName "Iosevka SS08"
    ParticipantFontColor #FFFFFF
}

hide footbox

participant "Agent" as A
participant "IConnector" as C

!ifdef SHOW_CONNECT || SHOW_DISCONNECT
participant "External System" as E
!endif

!ifdef SHOW_PRECONNECT
[-> A: Request for\nConnection Form
activate A
A -> C: PreConnect()
activate C
C --> A: Serialized Connection Form
deactivate C
deactivate A
!endif

!ifdef SHOW_CONNECT
|||
... User fills Connection Form with credentials and press "OK" ...

[-> A: Request for\nTest Connection\nwith credentials
activate A
A -> C: Connect(credentials)
activate C
C -> C: IsConnected = false
C -> E: Auth with credentials
activate E
E --> C: Auth Result
C -> C: IsConnected = Auth Result
deactivate E
C --> A
A -> C: Read IsConnected 
[<-- A: Return\nIsConnected 
deactivate C
deactivate A
!endif

!ifdef SHOW_DISCONNECT
A -> C: Disconnect(credentials)
activate A
activate C
C -> E: Close Connection
C -> C: Clean Resources
C -> C: IsConnected = false
activate E
E --> C
C --> A
deactivate E
[<-- A: \t\t
deactivate E
deactivate C
!endif

@enduml
